background {
  monitor = # monitor-agnostic
  path = /home/archslayer/Pictures/Wallpapers/FreeBSD.jpeg
  blur_passes = 1
  blur_size = 7
}


input-field {
  monitor =
  size = 20%, 5%
  font_family = Noto Sans
  dots_size = 0.20
  rounding = 0
  capslock_color = #EF4444
  outer_color = rgb(0, 0, 0)
  check_color = rgb(0, 0, 0)
  fail_color = rgb(0, 0, 0)
  position = 20, 20
  halign = left
  valign = bottom
}

label {
  monitor =
  text = $TIME
  font_size = 100
  position = 20, 100
  halign = left
  valign = center
}
